<a href="https://colab.research.google.com/github/prchlmrie/Colab_Notebooks/blob/main/Bikes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing packages
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")
sns.set_context("poster")
pd.options.display.float_format = '{:.2f}'.format

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
#Setup the initial data variables and load the dataset. Python starts with 0
df = pd.read_excel('/content/drive/MyDrive/Colab notebooks/Example - Analytics/Lab Dataset.xlsx', header=0)
df_FE = df
df.head() #view first 5 lines of the data

,Date,Customer Age,Customer Gender,Region,City/Municipality,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue
0,2015-01-01,19,F,AAAAA,1,Bikes,Road Bikes,1,45870.00,43026.06,45870.00,43026.06
1,2015-01-01,53,F,BBBBB,13,Bikes,Road Bikes,1,100088.34,107886.24,100088.34,107886.24
2,2015-01-01,36,F,AAAAA,2,Bikes,Mountain Bikes,2,47498.38,41099.52,94996.77,82199.04
3,2015-01-01,29,F,AAAAA,35,Bikes,Road Bikes,3,11972.07,10580.68,35916.21,31742.04
4,2015-01-01,29,M,AAAAA,3,Bikes,Road Bikes,3,11972.07,10687.71,35916.21,32063.13

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
#Analyze null values
df.isnull().sum()

Date                 0
Customer Age         0
Customer Gender      0
Region               0
City/Municipality    0
Product Category     0
Sub Category         0
Quantity             0
Unit Cost            0
Unit Price           0
Cost                 0
Revenue              0
dtype: int64

In [ ]:
#Check datatypes of columns. Read pandas datatypes.
#datetime = date, object = string, float(values that have decimals), int(no decimals) = numbers.
df_FE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34866 entries, 0 to 34865
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               34866 non-null  datetime64[ns]
 1   Customer Age       34866 non-null  int64
 2   Customer Gender    34866 non-null  object
 3   Region             34866 non-null  object
 4   City/Municipality  34866 non-null  int64
 5   Product Category   34866 non-null  object
 6   Sub Category       34866 non-null  object
 7   Quantity           34866 non-null  int64
 8   Unit Cost          34866 non-null  float64
 9   Unit Price         34866 non-null  float64
 10  Cost               34866 non-null  float64
 11  Revenue            34866 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(3), object(4)
memory usage: 3.2+ MB

In [ ]:
df['City/Municipality'] = df['City/Municipality'].astype(object)

In [ ]:
df_FE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34866 entries, 0 to 34865
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               34866 non-null  datetime64[ns]
 1   Customer Age       34866 non-null  int64
 2   Customer Gender    34866 non-null  object
 3   Region             34866 non-null  object
 4   City/Municipality  34866 non-null  object
 5   Product Category   34866 non-null  object
 6   Sub Category       34866 non-null  object
 7   Quantity           34866 non-null  int64
 8   Unit Cost          34866 non-null  float64
 9   Unit Price         34866 non-null  float64
 10  Cost               34866 non-null  float64
 11  Revenue            34866 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(2), object(5)
memory usage: 3.2+ MB

In [ ]:
#Check unique values
df['Sub Category'].unique()

array(['Road Bikes', 'Mountain Bikes', 'Bottles and Cages',
       'Tires and Tubes', 'Helmets', 'Jerseys', 'Bike Stands',
       'Touring Bikes', 'Caps', 'Socks', 'Hydration Packs', 'Vests',
       'Cleaners', 'Shorts', 'Fenders', 'Gloves', 'Bike Racks'],
      dtype=object)

In [ ]:
#correct wrong spelling
df['Sub Category'].replace('Fedners', 'Fenders', inplace=True)

<ipython-input-10-b4390ceb05b0>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sub Category'].replace('Fedners', 'Fenders', inplace=True)

In [ ]:
#Get summary statistics of columns
df.describe(exclude=['object'])

,Date,Customer Age,Quantity,Unit Cost,Unit Price,Cost,Revenue
count,34866,34866.00,34866.00,34866.00,34866.00,34866.00,34866.00
mean,2016-01-19 18:35:05.110996224,36.38,2.00,16049.02,17854.09,26421.33,29396.71
min,2015-01-01 00:00:00,17.00,1.00,30.73,30.58,91.74,91.74
25%,2015-10-26 00:00:00,28.00,1.00,2064.15,2461.69,3898.95,4678.74
50%,2016-01-28 00:00:00,35.00,2.00,6880.50,8210.73,11972.07,14632.53
75%,2016-04-26 00:00:00,44.00,3.00,20870.85,23898.27,35274.03,41374.74
max,2016-07-31 00:00:00,87.00,3.00,148618.80,233111.34,165132.00,233111.34
std,NaN,11.11,0.81,22477.03,24096.39,31673.25,33790.16

In [ ]:
#Get bike records. Filtering example
df_bikes = df[df['Product Category'] == 'Bikes']

In [ ]:
#Check for duplicated records
duplicate = df[df.duplicated()]
duplicate

,Date,Customer Age,Customer Gender,Region,City/Municipality,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue
2729,2015-08-12,43,F,DDDDD,12,Accessories,Bottles and Cages,2,458.70,642.18,917.40,1284.36

In [ ]:
#drop duplicated records
df.drop([2729], inplace=True)
df[df.duplicated()]

Empty DataFrame
Columns: [Date, Customer Age, Customer Gender, Region, City/Municipality, Product Category, Sub Category, Quantity, Unit Cost, Unit Price, Cost, Revenue]
Index: []

### Feature Engineering

In [ ]:
#Add profit column
df_FE['profit'] = df_FE['Revenue'] - df_FE['Cost']
df.head()

,Date,Customer Age,Customer Gender,Region,City/Municipality,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue,profit
0,2015-01-01,19,F,AAAAA,1,Bikes,Road Bikes,1,45870.00,43026.06,45870.00,43026.06,-2843.94
1,2015-01-01,53,F,BBBBB,13,Bikes,Road Bikes,1,100088.34,107886.24,100088.34,107886.24,7797.90
2,2015-01-01,36,F,AAAAA,2,Bikes,Mountain Bikes,2,47498.38,41099.52,94996.77,82199.04,-12797.73
3,2015-01-01,29,F,AAAAA,35,Bikes,Road Bikes,3,11972.07,10580.68,35916.21,31742.04,-4174.17
4,2015-01-01,29,M,AAAAA,3,Bikes,Road Bikes,3,11972.07,10687.71,35916.21,32063.13,-3853.08

In [ ]:
#Generating a function that defines age bracket
def age_bracket(age):
    if age >= 77 and age <= 94:
        return('Silent Generation (77-94)')
    if age >= 58  and age <= 76:
        return('Baby Boomers (58-76)')
    if age >=42   and age <= 57:
        return('Gen X (42-57)')
    if age >=26   and age <= 41:
        return('Millenials (26-41)')
    if age >=10   and age <= 25:
        return('Gen Z (10-25)')

In [ ]:
#Adding Age Bracket column
df_FE['Age Bracket'] = [age_bracket(x) for x in df['Customer Age']]
df_FE.head()

,Date,Customer Age,Customer Gender,Region,City/Municipality,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue,profit,Age Bracket
0,2015-01-01,19,F,AAAAA,1,Bikes,Road Bikes,1,45870.00,43026.06,45870.00,43026.06,-2843.94,Gen Z (10-25)
1,2015-01-01,53,F,BBBBB,13,Bikes,Road Bikes,1,100088.34,107886.24,100088.34,107886.24,7797.90,Gen X (42-57)
2,2015-01-01,36,F,AAAAA,2,Bikes,Mountain Bikes,2,47498.38,41099.52,94996.77,82199.04,-12797.73,Millenials (26-41)
3,2015-01-01,29,F,AAAAA,35,Bikes,Road Bikes,3,11972.07,10580.68,35916.21,31742.04,-4174.17,Millenials (26-41)
4,2015-01-01,29,M,AAAAA,3,Bikes,Road Bikes,3,11972.07,10687.71,35916.21,32063.13,-3853.08,Millenials (26-41)

In [ ]:
df_FE['Age Bracket'].unique()

array(['Gen Z (10-25)', 'Gen X (42-57)', 'Millenials (26-41)',
       'Baby Boomers (58-76)', 'Silent Generation (77-94)'], dtype=object)

In [ ]:
#Dividing into month, year, and quarter
df_FE['Month'] = pd.DatetimeIndex(df_FE['Date']).month
df_FE['Year'] = pd.DatetimeIndex(df_FE['Date']).year
df_FE['Quarter'] =  pd.PeriodIndex(df_FE['Date'], freq='Q')
df_FE.head()

,Date,Customer Age,Customer Gender,Region,City/Municipality,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue,profit,Age Bracket,Month,Year,Quarter
0,2015-01-01,19,F,AAAAA,1,Bikes,Road Bikes,1,45870.00,43026.06,45870.00,43026.06,-2843.94,Gen Z (10-25),1,2015,2015Q1
1,2015-01-01,53,F,BBBBB,13,Bikes,Road Bikes,1,100088.34,107886.24,100088.34,107886.24,7797.90,Gen X (42-57),1,2015,2015Q1
2,2015-01-01,36,F,AAAAA,2,Bikes,Mountain Bikes,2,47498.38,41099.52,94996.77,82199.04,-12797.73,Millenials (26-41),1,2015,2015Q1
3,2015-01-01,29,F,AAAAA,35,Bikes,Road Bikes,3,11972.07,10580.68,35916.21,31742.04,-4174.17,Millenials (26-41),1,2015,2015Q1
4,2015-01-01,29,M,AAAAA,3,Bikes,Road Bikes,3,11972.07,10687.71,35916.21,32063.13,-3853.08,Millenials (26-41),1,2015,2015Q1

In [ ]:
df_FE = df_FE.astype({"City/Municipality": str})

# Analysis Part

Answer guide questions:
 - Revenue and profit: What is the revenue and profit for year 2016?
 - Age group rankings
 - Product Category rankings

In [ ]:
#Market Share questions: What is the revenue and profit for year 2016?
#Operations/functions = (). Dataframe manipulation/filtering = []
tot_revenue_2016 = df_FE['Revenue'][df_FE['Year'] == 2016].sum()
profit_2016 = (df_FE['Revenue'][df_FE['Year'] == 2016].sum()) - (df_FE['Cost'][df_FE['Year'] == 2016].sum())


print("Total Revenue 2016: %5.2f" %(tot_revenue_2016))
print("Total Profit: %1d" % (profit_2016))

Total Revenue 2016: 568641445.35
Total Profit: 90500684

In [ ]:
bblab = 'Baby Boomers (58-76)'
gxlab = 'Gen X (42-57)'
gzlab = 'Gen Z (10-25)'
millab = 'Millenials (26-41)'
sglab = 'Silent Generation (77-94)'

In [ ]:
#Region questions: What are the profit, and number of transactions per region?
revenue = df_FE[['Region', 'profit', 'Revenue']].groupby(['Region']).agg({'Revenue': [sum], 'profit': [sum]})
revenue['Profit Margin(%)'] = revenue['profit']/revenue['Revenue'] * 100
revenue.sort_values(by=['Profit Margin(%)'], ascending = False)

<ipython-input-22-ae10dcd93957>:2: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  revenue = df_FE[['Region', 'profit', 'Revenue']].groupby(['Region']).agg({'Revenue': [sum], 'profit': [sum]})
<ipython-input-22-ae10dcd93957>:2: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  revenue = df_FE[['Region', 'profit', 'Revenue']].groupby(['Region']).agg({'Revenue': [sum], 'profit': [sum]})

            Revenue      profit Profit Margin(%)
                sum         sum
Region
DDDDD  194694389.34 43980935.79            22.59
BBBBB  158072790.48 12506776.59             7.91
CCCCC  196150211.40 15089165.85             7.69
AAAAA  476027025.54 32162438.55             6.76

In [ ]:
#Product Category Questions: What are the revenue per product_category per region?
revenue = df_FE[['Region', 'Product Category', 'profit', 'Revenue']].groupby(['Region', 'Product Category']).agg({'Revenue': [sum], 'profit': [sum], 'Region': ['count']})
revenue['Profit Margin(%)'] = revenue['profit']/revenue['Revenue'] * 100
revenue.rename(columns={"Region": 'Transactions'}, inplace=True)
revenue.sort_values(by=['Profit Margin(%)'], ascending = False)

<ipython-input-23-25a79fff4465>:2: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  revenue = df_FE[['Region', 'Product Category', 'profit', 'Revenue']].groupby(['Region', 'Product Category']).agg({'Revenue': [sum], 'profit': [sum], 'Region': ['count']})
<ipython-input-23-25a79fff4465>:2: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  revenue = df_FE[['Region', 'Product Category', 'profit', 'Revenue']].groupby(['Region', 'Product Category']).agg({'Revenue': [sum], 'profit': [sum], 'Region': ['count']})

                             Revenue      profit Transactions Profit Margin(%)
                                 sum         sum        count
Region Product Category
DDDDD  Accessories       59143952.34 18274378.65         3199            30.90
       Clothing          22461300.51  6621472.11          710            29.48
BBBBB  Accessories       50419248.99  8883138.33         3293            17.62
CCCCC  Accessories       60046031.76 10412398.26         3986            17.34
DDDDD  Bikes            113089136.49 19085085.03         1291            16.88
CCCCC  Clothing          25322762.85  3959773.62          938            15.64
AAAAA  Accessories      170775340.23 25673851.83        12055            15.03
BBBBB  Clothing          21757241.88  2951000.58          723            13.56
AAAAA  Clothing          88139434.35 11477545.53         2868            13.02
BBBBB  Bikes             85896299.61   672637.68         1152             0.78
CCCCC  Bikes            110781416.79   716993.97         1497             0.65
AAAAA  Bikes            217112250.96 -4988958.81         3153            -2.30

In [ ]:
#Age group - Rank product category rankings
test_output = df_FE[['Customer Gender', 'Age Bracket', 'Product Category', 'Revenue', 'profit']].groupby(['Customer Gender', 'Age Bracket', 'Product Category']).agg({'Revenue': [sum, np.mean], 'profit': [sum, np.mean]})
test_output

<ipython-input-24-671d2bc572c2>:2: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  test_output = df_FE[['Customer Gender', 'Age Bracket', 'Product Category', 'Revenue', 'profit']].groupby(['Customer Gender', 'Age Bracket', 'Product Category']).agg({'Revenue': [sum, np.mean], 'profit': [sum, np.mean]})
<ipython-input-24-671d2bc572c2>:2: FutureWarning: The provided callable <function mean at 0x7afb569015a0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  test_output = df_FE[['Customer Gender', 'Age Bracket', 'Product Category', 'Revenue', 'profit']].groupby(['Customer Gender', 'Age Bracket', 'Product Category']).agg({'Revenue': [sum, np.mean], 'profit': [sum, np.mean]})
<ipython-input-24-671d2bc572c2>:2: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  test_output = df_FE[['Customer Gender', 'Age Bracket', 'Product Category', 'Revenue', 'profit']].groupby(['Customer Gender', 'Age Bracket', 'Product Category']).agg({'Revenue': [sum, np.mean], 'profit': [sum, np.mean]})

                                                                Revenue  \
                                                                    sum
Customer Gender Age Bracket               Product Category
F               Baby Boomers (58-76)      Accessories        7233056.82
                                          Bikes              5947091.37
                                          Clothing           2621332.89
                Gen X (42-57)             Accessories       49377174.33
                                          Bikes             69597129.03
                                          Clothing          21499865.31
                Gen Z (10-25)             Accessories       25088413.02
                                          Bikes             28178078.61
                                          Clothing          12546041.31
                Millenials (26-41)        Accessories       82293715.68
                                          Bikes            159056885.46
                                          Clothing          37505834.85
                Silent Generation (77-94) Accessories         384161.25
                                          Clothing            149857.29
M               Baby Boomers (58-76)      Accessories        6694634.76
                                          Bikes              6124516.53
                                          Clothing           4105686.09
                Gen X (42-57)             Accessories       48788111.79
                                          Bikes             72976830.63
                                          Clothing          21945996.93
                Gen Z (10-25)             Accessories       32943145.95
                                          Bikes             31657134.63
                                          Clothing          13668159.12
                Millenials (26-41)        Accessories       87355240.83
                                          Bikes            153341437.59
                                          Clothing          43479072.12
                Silent Generation (77-94) Accessories         226918.89
                                          Clothing            158893.68

                                                                     \
                                                               mean
Customer Gender Age Bracket               Product Category
F               Baby Boomers (58-76)      Accessories      15356.81
                                          Bikes            79294.55
                                          Clothing         31206.34
                Gen X (42-57)             Accessories      15805.75
                                          Bikes            80645.57
                                          Clothing         30802.10
                Gen Z (10-25)             Accessories      12619.93
                                          Bikes            69404.13
                                          Clothing         28907.93
                Millenials (26-41)        Accessories      15158.17
                                          Bikes            73298.10
                                          Clothing         29255.72
                Silent Generation (77-94) Accessories      13246.94
                                          Clothing         21408.18
M               Baby Boomers (58-76)      Accessories      13976.27
                                          Bikes            82763.74
                                          Clothing         36657.91
                Gen X (42-57)             Accessories      15449.05
                                          Bikes            83785.11
                                          Clothing         31041.01
                Gen Z (10-25)             Accessories      14493.25
                                          Bikes            66228.32
                                          Clothing         27501.33
                Millenials (26-41)        Accessories      15708.55
                                          Bikes            71123.12
                                          Clothing         30705.56
                Silent Generation (77-94) Accessories      10805.66
                                          Clothing         79446.84

                                                                profit  \
                                                                   sum
Customer Gender Age Bracket               Product Category
F               Baby Boomers (58-76)      Accessories       1303258.44
                                          Bikes               -7476.81
                                          Clothing           368794.80
                Gen X (42-57)             Accessories       9215328.87
                                          Bikes             2155614.78
                                          Clothing          3510476.97
                Gen Z (10-25)             Accessories       4586495.43
                                          Bikes             1197573.96
                                          Clothing          1912366.17
                Millenials (26-41)        Accessories      15308378.58
                                          Bikes             4813276.71
                                          Clothing          5895395.88
                Silent Generation (77-94) Accessories         89400.63
                                          Clothing            32063.13
M               Baby Boomers (58-76)      Accessories       1198812.45
                                          Bikes             -161645.88
                                          Clothing           502781.07
                Gen X (42-57)             Accessories       8838644.43
                                          Bikes             2144514.24
                                          Clothing          3481716.48
                Gen Z (10-25)             Accessories       6143369.10
                                          Bikes              878593.98
                                          Clothing          1919659.50
                Millenials (26-41)        Accessories      16515539.37
                                          Bikes             4465306.89
                                          Clothing          7326723.36
                Silent Generation (77-94) Accessories         44539.77
                                          Clothing            59814.48


                                                               mean
Customer Gender Age Bracket               Product Category
F               Baby Boomers (58-76)      Accessories       2767.00
                                          Bikes              -99.69
                                          Clothing          4390.41
                Gen X (42-57)             Accessories       2949.85
                                          Bikes             2497.82
                                          Clothing          5029.34
                Gen Z (10-25)             Accessories       2307.09
                                          Bikes             2949.69
                                          Clothing          4406.37
                Millenials (26-41)        Accessories       2819.74
                                          Bikes             2218.10
                                          Clothing          4598.59
                Silent Generation (77-94) Accessories       3082.78
                                          Clothing          4580.45
M               Baby Boomers (58-76)      Accessories       2502.74
                                          Bikes            -2184.40
                                          Clothing          4489.12
                Gen X (42-57)             Accessories       2798.81
                                          Bikes             2462.13
                                          Clothing          4924.63
                Gen Z (10-25)             Accessories       2702.76
                                          Bikes             1838.06
                                          Clothing          3862.49
                Millenials (26-41)        Accessories       2969.89
                                          Bikes             2071.11
                                          Clothing          5174.24
                Silent Generation (77-94) Accessories       2120.94
                                          Clothing         29907.24

In [ ]:
#Save output to CSV
test_output.to_csv('/content/drive/MyDrive/Colab Notebooks/Example - Analytics/Lab Dataset - preprocessed.csv', index=True)

OSError: Cannot save file into a non-existent directory: '/content/drive/MyDrive/Colab Notebooks/Example - Analytics'

In [ ]:
#Save output to excel
test_output.to_excel('/content/drive/MyDrive/Colab Notebooks/Example - Analytics/aggregated.xlsx', index=True)